### ISSUE TITLE
LabelPlus 

### ISSUE THREAD

**Issue by danaja75** [Amar1729/homebrew-deluge-meta#14]
My plugin not show. On thinclient under windows 10 plugin work flawless

**Comment by Amar1729** [comment]
If you're using the thinclient installed by this package (i.e. connecting to a running daemon) then you should ensure your plugins are installed properly on the host.

If using this app as "Standalone", then you'll still have to install the plugin .eggs into deluge's app directory, which will be somewhere under the homebrew Cellar (e.g. `/opt/homebrew/Cellar/deluge-meta` on an ARM mac)
