### ISSUE TITLE
Add LaunchAgent

### ISSUE THREAD

**Issue by grigarr** [Amar1729/homebrew-deluge-meta#18]
**Describe the bug**
I've been using your build on my M1 Mac Mini in a headless way. It works great, but to streamline the startup of deluged I needed a LaunchAgent plist file (see below). I'm not familiar with homebrew but wanted to drop this here in case it's helpful for others

**Additional context**
` ~/Library/LaunchAgents/homebrew.mxcl.deluged.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.deluged</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/deluge-meta/bin/deluged</string>
		<string>--do-not-daemonize</string>
		<string>--loglevel</string>
		<string>info</string>
		<string>--logfile</string>
		<string>/opt/homebrew/var/deluge-meta/deluged.log</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

This also requires creating `/opt/homebrew/var/deluge-meta/` in order to log in that location. I copied the general structure from the transmission-cli plist (which hopefully follows standard convention).

**Comment by Amar1729** [comment]
Bit of a pain updating CI with the newer env vars homebrew-core uses, but I finally got it to work. You should be able to start `deluge` with `brew services` now. Thanks for the writeup!
