### ISSUE TITLE
running brew install amar1729/deluge-meta/deluge-meta errors out

### ISSUE THREAD

**Issue by spitfire** [Amar1729/homebrew-deluge-meta#25]
**Describe the bug**
Running `brew install amar1729/deluge-meta/deluge-meta`  results in `Error: python-typing-extensions has been disabled because it does not meet homebrew/core's requirements for Python library formulae! It was disabled on 2024-07-05.`

**Desktop (please complete the following information):**
 - macOS Version: 14.6.1

**Comment by Amar1729** [comment]
Will be fixed by #23
