### ISSUE TITLE
Provide App Bundle for deluge-gtk

### ISSUE THREAD

**Issue by eatyourbaby** [Amar1729/homebrew-deluge-meta#28]
App bundle allows bash script, and we can create a shim to run `deluge-gtk` the usual way, instead of running from terminal every time. You can find such an app bundle below. `Info.plist` and icons taken from the official app bundle 1.3.15.1.

[Deluge.zip](https://github.com/user-attachments/files/17157677/Deluge.zip)

I've been using this for a long time now. Just realized people might benefit from it so I wanted to share it. Might be helpful if included in README.

**Comment by Amar1729** [comment]
Thanks for the idea. I think there would have to be some helper script to generate the .app bundle, since i don't think homebrew formulae are allowed to write into `/Applications`. Not opposed to the idea, just haven't gotten around to it.

**Comment by eatyourbaby** [comment]
Got it. I just wanted to share a way to run `deluge-gtk` the usual way, because running a GUI application from terminal is suboptimial.

Out of curiosity, I tried to create an actual portable app bundle bootstrapped by your brew formula, and it seems doable. Deluge 1.x used `py2app` for packaging, but it wasn't cooperating with me easily. I switched to `pyinstaller` instead and produced an app bundle that mostly worked (only `deluge-gtk` is exposed and plugins are known broken). 
[Deluge_2.1.1.dev127_arm64-apple-darwin24.zip](https://github.com/user-attachments/files/17198004/Deluge_2.1.1.dev127_arm64-apple-darwin24.zip)

I'll look into it later when I have time. I might be able to create a PR to produce app bundles with GitHub Actions. There are also some patches I need to submit to upstream first to fix `gtk-mac-integration`.

**Comment by cipri-tom** [comment]
I know nothing about brew, but I install many apps in `/Applications` with it. For example, Firefox, 1password, gimp, google chrome, iterm2, spotify ... All the things I use are installed with brew, so I'm pretty sure it _can_ write in Applications

**Comment by eatyourbaby** [comment]
@cipri-tom What I proposed is just a workaround, and now it seems like properly packaging Deluge is possible, so I'll look into that instead when I have time. I'll close the issue for now.
