### ISSUE TITLE
"Python quit unexpectedl"

### ISSUE THREAD

**Issue by serovar** [Amar1729/homebrew-deluge-meta#8]
I installed deluge-meta through brew and everything went fine, but when I launch `deluge-gtk` I get the "Python quit unexpectedly" popup and this error on the terminal:

`Unable to initialize gettext/locale!
'ngettext'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/deluge-meta/2.0.3_2/libexec/lib/python3.9/site-packages/deluge/i18n/util.py", line 118, in setup_translation`
    `builtins.__dict__['_n'] = builtins.__dict__['ngettext']`
`KeyError: 'ngettext'`
``zsh: segmentation fault  deluge-gtk``

**Comment by Amar1729** [comment]
Weird. It's possible the bottle is outdated - can you try building from source instead?

`brew install -s amar1729/deluge-meta/deluge-meta`

**Comment by Amar1729** [comment]
Closing this - I have a feeling this err may have been due to a library having a problem somehow on arm architecture (I see your homebrew path starts with `/opt`). Feel free to open a new issue if you see other problems.
